version: "3.4"

services:
  truffle:
    build:
      context: ./contracts
    depends_on:
      - ganache
    volumes:
      - ./contracts:/home/app
      - /home/app/node_modules
  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - 8545:8545
    volumes:
      - ganache:/app/chaindb

volumes:
  ganache: